/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mywebmanager.views;

/**
 *
 * @author Calci
 */
public class Prueva2 extends javax.swing.JPanel {

    /**
     * Creates new form Prueva2
     */
    public Prueva2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDegradado1 = new com.mywebmanager.swings.JComponents.PanelDegradado();
        panelDegradado2 = new com.mywebmanager.swings.JComponents.PanelDegradado();
        labelTituloBackground = new com.mywebmanager.swings.JComponents.Label.LabelText();
        jSeparator1 = new javax.swing.JSeparator();
        labelTextColores = new com.mywebmanager.swings.JComponents.Label.LabelText();
        labelText1 = new com.mywebmanager.swings.JComponents.Label.LabelText();
        botonColor1 = new com.mywebmanager.swings.JComponents.BotonColor();
        botonColor2 = new com.mywebmanager.swings.JComponents.BotonColor();
        botonColor3 = new com.mywebmanager.swings.JComponents.BotonColor();
        botonColor4 = new com.mywebmanager.swings.JComponents.BotonColor();

        labelTituloBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloBackground.setText("Diseño de Fondo");
        labelTituloBackground.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N

        javax.swing.GroupLayout panelDegradado2Layout = new javax.swing.GroupLayout(panelDegradado2);
        panelDegradado2.setLayout(panelDegradado2Layout);
        panelDegradado2Layout.setHorizontalGroup(
            panelDegradado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTituloBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDegradado2Layout.setVerticalGroup(
            panelDegradado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDegradado2Layout.createSequentialGroup()
                .addComponent(labelTituloBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        labelTextColores.setText("Colores de Fondo");
        labelTextColores.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N

        labelText1.setText("Fracciones de Colores");
        labelText1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N

        botonColor1.setText("Color 1");

        botonColor2.setText("Color 2");

        botonColor3.setText("Color 3");
        botonColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonColor3ActionPerformed(evt);
            }
        });

        botonColor4.setText("Color 4");

        javax.swing.GroupLayout panelDegradado1Layout = new javax.swing.GroupLayout(panelDegradado1);
        panelDegradado1.setLayout(panelDegradado1Layout);
        panelDegradado1Layout.setHorizontalGroup(
            panelDegradado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDegradado1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDegradado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelDegradado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDegradado1Layout.createSequentialGroup()
                        .addGroup(panelDegradado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDegradado1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelTextColores, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                            .addGroup(panelDegradado1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(botonColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(botonColor2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(botonColor3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(botonColor4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(12, 12, 12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelText1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDegradado1Layout.setVerticalGroup(
            panelDegradado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDegradado1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDegradado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDegradado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDegradado1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addGap(18, 18, 18))
                    .addGroup(panelDegradado1Layout.createSequentialGroup()
                        .addGroup(panelDegradado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTextColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDegradado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonColor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonColor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonColor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(147, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDegradado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDegradado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonColor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonColor3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mywebmanager.swings.JComponents.BotonColor botonColor1;
    private com.mywebmanager.swings.JComponents.BotonColor botonColor2;
    private com.mywebmanager.swings.JComponents.BotonColor botonColor3;
    private com.mywebmanager.swings.JComponents.BotonColor botonColor4;
    private javax.swing.JSeparator jSeparator1;
    private com.mywebmanager.swings.JComponents.Label.LabelText labelText1;
    private com.mywebmanager.swings.JComponents.Label.LabelText labelTextColores;
    private com.mywebmanager.swings.JComponents.Label.LabelText labelTituloBackground;
    private com.mywebmanager.swings.JComponents.PanelDegradado panelDegradado1;
    private com.mywebmanager.swings.JComponents.PanelDegradado panelDegradado2;
    // End of variables declaration//GEN-END:variables
}
